runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /populateDatabase
  script: main.app
  login: admin
- url: /.*
  script: main.app
  login: required

#http://localhost:8080/_ah/login

libraries:
  - name: jinja2
    version: latest
